# Site settings
title: ""                # Leave blank to avoid header text
description: ""          # Leave blank to avoid subtitle text
url: "https://craven-68.github.io"   # Replace with your GitHub Pages URL
baseurl: "/craven.github.io"              # Keep empty for user/organization site

# Theme
# theme: jekyll-theme-cayman

# Add custom CSS
include:
  - assets

# Build settings
markdown: kramdown       # Recommended markdown processor
plugins:
  - jekyll-seo-tag       # Adds SEO metadata
  - jekyll-sitemap       # Generates sitemap for search engines

# Author info (placeholders)
author:
  name: "Your Name"
  email: "your.email@example.com"
  github: "yourusername"
  linkedin: "your-linkedin-url"
